name: Ci

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .

  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Luacheck
        uses: lunarmodules/luacheck@v0.26.0

  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: mutchar.nvim
          treesitter: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(doc): auto generate docs'
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - run: luarocks --lua-version=5.1 install vusted
      - run: vuste ./tests/mutchar_spec.lua
